communitiesuk/eip-ero-ems-integration-api

- src/main/resources/db/changelog/create/0012_EIP1-6836_modify_remaining_rejection_reasons.xml
- src/main/resources/db/changelog/db.changelog-master.yaml
Migration 11 updated length for `<english|welsh>_rejection_notes` but a duplication mistake meant it was only one language per application process rather than both. This new migration increases the corresponding length for the other language.
> [EIP1-6836] Increase rejection notes for other language initially missed

- src/main/resources/db/changelog/create/0013_EIP1-7400_add_index_on_date_created.xml
- src/main/resources/db/changelog/db.changelog-master.yaml
Add index on date_created to application tables to fix bug for some EROs. Was previously possibly to exhaust sort buffer with signature data when ERO was across many GSS codes due to query plan used.
> EIP1-7400 Add index on date_created to application tables to fix issue

- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/database/repository/PostalVoteApplicationRepository.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/database/repository/ProxyVoteApplicationRepository.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/service/PostalVoteApplicationService.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/service/ProxyVoteApplicationService.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/database/repository/PostalVoteApplicationRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/database/repository/ProxyVoteApplicationRepositoryIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/service/PostalVoteApplicationServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/service/ProxyVoteApplicationServiceTest.kt
Issue still being caused when sort buffer used as full application loaded into memory including signature data. Sorting to find suitable applications returning only application ID and then full applications unsorted as a two step process should avoid this as only sorting smaller set of data and then fetching larger data set without any sorting
> EIP1-7400 Use two step process to avoid sort buffer issues

- src/main/resources/openapi/EMSIntegrationAPIs.yaml
The following draft PR is for review and should not be considered final.
This will be discussed and reviewed internally and if appropriate sent to EMS vendors for review.
Notes:
postalProxy: if accepted, this will be added to the contract but will not be populated until EMSs support this feature.
rejectedReasons: again if accepted, the supports backward compatibility until EMSs all support the new rejected reasons structure allowing them to include/exclude reasons for elector comms.
> postalProxy and extended rejected reasons to include 'includeInComms' flag

- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/database/entity/ApplicationDetails.kt
- src/main/resources/db/changelog/create/0017_EROPSPT-186_increase_signature_waived_reason_max_length.xml
- src/main/resources/db/changelog/db.changelog-master.yaml
- src/main/resources/openapi/sqs/Models/ApplicationDetails.yaml
- src/main/resources/openapi/sqs/postal-vote-application-sqs-messaging.yaml
- src/main/resources/openapi/sqs/proxy-vote-application-sqs-messaging.yaml
- src/test/resources/features/save-postal-vote-application.feature
- src/test/resources/features/save-proxy-vote-application.feature
Currently there is a mismatch between EMS integration api and the rest of the system on the maximum length of a signature waived reason:
- The max elector facing length is 250 characters
- Some explanatory characters are then added to the beginning of this by IER
- The rest of EROP assumes these explanatory characters are there, taking the max length up to 327
- The specification for connecting EMS's says there will be at most 500 characters that they receive
- BUT the EMS integration API specification and database are configured to allow only 250 characters.
Therefore some messages being received by EMS integration API are too long and end up on the DLQ so never get downloaded by EMSes.
Bumping this up to 500 characters makes everything consistent and should fix the bug.
> EROPSPT-186: Increase the limit from 250 characters to 500 characters for signatureWaivedReasons

- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/config/ApiProperties.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/service/PostalVoteApplicationService.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/service/ProxyVoteApplicationService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/config/ApiPropertiesTest.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/rest/PageSizeValidatorTest.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/service/PostalVoteApplicationServiceTest.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/service/ProxyVoteApplicationServiceTest.kt
- src/test/resources/application-integration-test.yml
Signatures are around 20KB on average, so a page size of 500 corresponds to around 10MB of data, which goes over the limit that can be passed through an API Gateway.
This change forces at most 200 applications to be returned, even if more than 200 applications are requested. Requests with a page size over 200 are still accepted, while EMS's are given time to adapt to the change.
> EROPSPT-274: Force a lower maximum page size (200)

- src/main/resources/openapi/EMSIntegrationAPIs.yaml
Barnsley appear to have been able to download some records this morning, so it seems like the new forced limit is working!
It would be good to get EMS's to make this change on their side eventually, as for example they might think they have got all of the records if they think the page size is 200. Duncan is writing a change request to share with EMS's, this is the change to the API spec.
> EROPSPT-274: Update API spec to reduce maximum pageSize to 200

- build.gradle.kts
- owasp.suppressions.xml
I grouped the results from the scanner into different types:
- Reported vulnerabilities that I believed were exploitable (this category was empty)
- Reported vulnerabilities that would be fixed by the pending Spring Boot 3 upgrade (these are suppressed with a note explaining so)
- Reported vulnerabilities that could be fixed with no risk to the application (these have been fixed)
- Reported vulnerabilities that would induce some amount of risk in fixing (these have been suppressed until immediately after elections, to be revisited at that time)
> EROPSPT-187 - Update suppressions after latest vuln scan

- src/main/resources/db/changelog/create/0020_EROPSPT-298_remove_date_created_index.xml
- src/main/resources/db/changelog/db.changelog-master.yaml
This index was originally created to resolve an issues where the sort buffer could be exhausted with signature data. A different fix was later added to implement a two-step retrieval process.
We have seen this index used inefficiently for finding ERO downloads on live - that problem was resolved by adding a new index. We've also seen this index used when the monitoring queries are running, and the queries run more slowly when using this index than when forced to use the index on gss code, status and date created.
---
There is some risk that the index is still doing something useful, so if we release this change we will want to monitor ems integration api for 5xx errors and reinstate the index if we see problems.
> EROPSPT-298: Remove index on date created

- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/database/entity/PendingDownloadsSummaryByGssCode.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/database/repository/PostalVoteApplicationRepository.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/database/repository/ProxyVoteApplicationRepository.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/service/PendingDownloadsMonitoringService.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/cucumber/database/PostalVoteApplicationSteps.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/cucumber/database/ProxyVoteApplicationSteps.kt
- src/test/resources/features/monitoring-pending-downloads.feature
This information is very useful for identifying genuine issues at the moment as some applications without an EMS Elector ID get put in a holding area on the EMS side, and do not get responded to until later. The EMS behaviour may change in the future as it comes with some problems, and these applications still need some attention paid to them, otherwise they can block other downloads.
> EROPSPT-298: Add information on presence of EMS Elector Ids in monitoring

- src/main/resources/application.yml
- src/test/resources/application-integration-test.yml
The monitoring job is failing on live, it seems sensible to disable it until after Enhanced Support and run the monitoring queries manually until then.
There is an error thrown around 45 seconds after the job starts: "Transaction resolution unknown. Please re-configure session state if required and restart transaction". It seems like it is hitting some kind of timeout or disconnect, but probably it is safer to just disable this job until after code freeze. The postal database query does appear to be running, and is showing up in the slow query logs as taking a bit more than 5 minutes.
> EROPSPT-298: Disable EMS Integration API monitoring job

- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/config/CorrelationIdMdcConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/config/IerRestTemplateConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/config/WebMvcConfig.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/logging/CorrelationIdMdcIntegrationTest.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/testsupport/WiremockService.kt
Code for CorrelationIdRestTemplateClientHttpRequestInterceptor copied from logging library - not sure why the shared libraries aren't used in newer services though, possibly I should be sorting that out as well but the tests are still helpful as the missing code was mostly configuration.
> EROPSPT-319: Add correlation ids to logging for api requests

- .github/workflows/build-image-and-deploy-to-dev.yml
The latest GitHub runner images have upgraded to Docker 26.
There's an incompatibility between Spring Boot 2 and Docker versions >= 25 when it comes to installing buildpacks, which causes bootBuildImage to fail.
Failed action: https://github.com/communitiesuk/eip-ero-ems-integration-api/actions/runs/9514574614
Issue thread: https://github.com/spring-projects/spring-boot/issues/39323
(Temporarily) downgrade to Docker 24 for as long as this project is not upgraded to SB 3. This will need to be replicated on the other SB 2 projects.
> EROPSPT-NONE - Downgrade Docker to fix building app images

- src/main/resources/db/changelog/create/0021_EROPSPT-350_remove_unused_indexes.xml
- src/main/resources/db/changelog/create/0022_EROPSPT-350_add_index_on_status.xml
- src/main/resources/db/changelog/db.changelog-master.yaml
Remove indexes:
- on application_id and gss_code - application_id is the primary key so this doesn't seem like it should be very useful
- on application_id and status - again, application_id is the primary key so it is hard to see how this could be useful
- on gss_code - there is an index on (gss_code, status, date_created) which is used for the most common queries, and I think this should be sufficient for occasional manual queries by gss_code only
Add an index on status to help getting a breakdown of applications in RECEIVED state - this will probably want adding manually to the live table as it will take more than a minute to run.
> EROPSPT-350: Review indexes on EMS integration API tables

- src/main/resources/openapi/EMSIntegrationAPIs.yaml
Documentation only, noticed when about to share the latest version it still had Krister as the contact so have updated to Duncan.
> EIP1-NONE Update EMS Integration API yaml contact details

- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/service/ProcessIntegrationDataRemovalMessageService.kt
- src/test/kotlin/uk/gov/dluhc/emsintegrationapi/service/ProcessIntegrationDataRemovalMessageServiceTest.kt
This is addressing a new acceptance criterion on https://mhclgdigital.atlassian.net/browse/EIP1-11125 :
> If a message is received on the remove-application-ems-integration-data queue and the application is not found then no exception is thrown and a warning message is logged
[See former PR](https://github.com/communitiesuk/eip-ero-ems-integration-api/pull/102).
> EIP1-11125: handling application not found on removal message

- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/service/ProcessIntegrationDataRemovalMessageService.kt
Correct application type that is logged when an application id for a proxy application supplied in a remove integration data message does not match to an existing application.
> EIP1-11125: correct application type on data removal warn logging statement

- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/service/ProcessIntegrationDataRemovalMessageService.kt
Logging message on processing a remove integration data message showed postal type application in every case whereas it should show postal or proxy depending on the context.  This has now been corrected to use `removeEmsDataMessage.source` enumerated value interpolated into the string logging output.
See JIRA item https://mhclgdigital.atlassian.net/browse/EIP1-11125.
> EIP1-11125: correct logging message

- docker/docker-compose.yml
- src/main/kotlin/uk/gov/dluhc/emsintegrationapi/config/IerRestTemplateConfiguration.kt
- src/main/resources/application.yml
- src/test/resources/application-integration-test.yml
Associated infra changes here: https://github.com/communitiesuk/eip-ero-infra/pull/2305/files.
I've tested that these same changes work in the proxy api.
These changes have been duplicated in the following repos:
- eip-ero-applications-api: https://github.com/communitiesuk/eip-ero-applications-api/pull/82
- eip-ero-ems-integration-api: https://github.com/communitiesuk/eip-ero-ems-integration-api/pull/122
- eip-ero-management-api: https://github.com/communitiesuk/eip-ero-management-api/pull/168
- eip-ero-register-checker-api: https://github.com/communitiesuk/eip-ero-register-checker-api/pull/160
- eip-ero-overseas-applications-api: https://github.com/communitiesuk/eip-ero-overseas-applications-api/pull/395
- eip-ero-postal-applications-api: …
> IERSPPRT-1549: Add external ID to assume ier client role

- .github/workflows/build-image-and-deploy-to-dev.yml
Issue is when there are `"` in the tag (commit) message, which is the default way `Revert` commits are formatted.
We have done the same fix of removing the tag message in other services for the same reason.
> EIP1-NONE: Remove tag message when pushing tag to avoid escape issues

- src/main/resources/application.yml
Made several corrections to env var expectations in `application.yml` for configuration of QS queues.
This PR is about making sure the ems integration api can deploy to DEV2 without infrastructural errors. It ties in with infra PR https://github.com/communitiesuk/eip-ero-infra/pull/2529 and should not be merged before that or the deployment will fail.
> EIP1-11113: change some sqs queue configurations

- build.gradle.kts
Upgrading SB to the latest 3.3 version. Resolves CVE-2025-22235 and CVE-2025-22228.
> EROPSPT-443: Upgrade SB to 3.3.11
